export const mockData = [
  {
    id: 1,
    from: 'MOVE',
    to: 'USDC.e',
    amount: '$1.53M',
    percentage: '63%',
    fromIcon: '/android-icon-48x48.png',
    toIcon: '/android-icon-48x48.png',
  },
  {
    id: 2,
    from: 'MOVE',
    to: 'USDC.e',
    amount: '$1.53M',
    percentage: '63%',
    fromIcon: '/android-icon-48x48.png',
    toIcon: '/android-icon-48x48.png',
  },
  {
    id: 3,
    from: 'MOVE',
    to: 'USDC.e',
    amount: '$1.53M',
    percentage: '63%',
    fromIcon: '/android-icon-48x48.png',
    toIcon: '/android-icon-48x48.png',
  },
  {
    id: 4,
    from: 'MOVE',
    to: 'USDC.e',
    amount: '$1.53M',
    percentage: '63%',
    fromIcon: '/android-icon-48x48.png',
    toIcon: '/android-icon-48x48.png',
  },
  {
    id: 5,
    from: 'MOVE',
    to: 'USDC.e',
    amount: '$1.53M',
    percentage: '63%',
    fromIcon: '/android-icon-48x48.png',
    toIcon: '/android-icon-48x48.png',
  },
  {
    id: 6,
    from: 'MOVE',
    to: 'USDC.e',
    amount: '$1.53M',
    percentage: '63%',
    fromIcon: '/android-icon-48x48.png',
    toIcon: '/android-icon-48x48.png',
  },
  {
    id: 7,
    from: 'MOVE',
    to: 'USDC.e',
    amount: '$1.53M',
    percentage: '63%',
    fromIcon: '/android-icon-48x48.png',
    toIcon: '/android-icon-48x48.png',
  },
];
